apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-digital
  description: handysnacks ecommsite
  annotations:
    github.com/project-slug: handysnacks/eComm
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: user: ecomm
  version: "1.0"

