apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-ecomm
  description: handysnacks ecommsite
  providesApi: petstore    
  annotations:
    github.com/project-slug: handysnacks/eComm
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: eComm
  version: "1.0"
  system: testing
  providesApis: 
    - petstore  
  dependsOn:
    - resource:default/artists-db
