apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: www-ecomm
  description: handysnacks ecommsite
  annotations:
    github.com/project-slug: eComm
spec:
  type: website
  lifecycle: production
  owner: user: ecomm
  version: "1.0"

